2gather:
  build: .

  ports:
    - "3000:3000"
    - "3005:3005"
    - "15254:15254"

  environment:
    - LOG_LEVEL=3
    - CONTAINERS=true

  links:
    - ipfs

  command: /home/eris/.decerver/dapps/2gather/spec/teststart.sh

ipfs:
  image: eris/ipfs

  volumes:
    - ~/.decerver/filesystems/ipfs:/root/.go-ipfs:rw

  ports:
    - "4001:4001"
    - "8080:8080"
